// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.1
// source: satellite.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionState int32

const (
	SessionState_SESSION_STATE_UNSPECIFIED  SessionState = 0
	SessionState_SESSION_STATE_STARTING     SessionState = 1
	SessionState_SESSION_STATE_RUNNING      SessionState = 2
	SessionState_SESSION_STATE_SUSPENDED    SessionState = 3
	SessionState_SESSION_STATE_TERMINATED   SessionState = 4
	SessionState_SESSION_STATE_ERROR        SessionState = 5
	SessionState_SESSION_STATE_DETACHED     SessionState = 6
	SessionState_SESSION_STATE_RE_ATTACHING SessionState = 7
)

// Enum value maps for SessionState.
var (
	SessionState_name = map[int32]string{
		0: "SESSION_STATE_UNSPECIFIED",
		1: "SESSION_STATE_STARTING",
		2: "SESSION_STATE_RUNNING",
		3: "SESSION_STATE_SUSPENDED",
		4: "SESSION_STATE_TERMINATED",
		5: "SESSION_STATE_ERROR",
		6: "SESSION_STATE_DETACHED",
		7: "SESSION_STATE_RE_ATTACHING",
	}
	SessionState_value = map[string]int32{
		"SESSION_STATE_UNSPECIFIED":  0,
		"SESSION_STATE_STARTING":     1,
		"SESSION_STATE_RUNNING":      2,
		"SESSION_STATE_SUSPENDED":    3,
		"SESSION_STATE_TERMINATED":   4,
		"SESSION_STATE_ERROR":        5,
		"SESSION_STATE_DETACHED":     6,
		"SESSION_STATE_RE_ATTACHING": 7,
	}
)

func (x SessionState) Enum() *SessionState {
	p := new(SessionState)
	*p = x
	return p
}

func (x SessionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionState) Descriptor() protoreflect.EnumDescriptor {
	return file_satellite_proto_enumTypes[0].Descriptor()
}

func (SessionState) Type() protoreflect.EnumType {
	return &file_satellite_proto_enumTypes[0]
}

func (x SessionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionState.Descriptor instead.
func (SessionState) EnumDescriptor() ([]byte, []int) {
	return file_satellite_proto_rawDescGZIP(), []int{0}
}

// RiskLevel indicates the severity of a proposed command
type RiskLevel int32

const (
	RiskLevel_RISK_LEVEL_UNSPECIFIED RiskLevel = 0
	RiskLevel_RISK_LEVEL_LOW         RiskLevel = 1 // Read-only commands, status checks
	RiskLevel_RISK_LEVEL_MEDIUM      RiskLevel = 2 // Service restarts, config changes
	RiskLevel_RISK_LEVEL_HIGH        RiskLevel = 3 // Data modifications, package installs
	RiskLevel_RISK_LEVEL_CRITICAL    RiskLevel = 4 // Destructive operations, system changes
)

// Enum value maps for RiskLevel.
var (
	RiskLevel_name = map[int32]string{
		0: "RISK_LEVEL_UNSPECIFIED",
		1: "RISK_LEVEL_LOW",
		2: "RISK_LEVEL_MEDIUM",
		3: "RISK_LEVEL_HIGH",
		4: "RISK_LEVEL_CRITICAL",
	}
	RiskLevel_value = map[string]int32{
		"RISK_LEVEL_UNSPECIFIED": 0,
		"RISK_LEVEL_LOW":         1,
		"RISK_LEVEL_MEDIUM":      2,
		"RISK_LEVEL_HIGH":        3,
		"RISK_LEVEL_CRITICAL":    4,
	}
)

func (x RiskLevel) Enum() *RiskLevel {
	p := new(RiskLevel)
	*p = x
	return p
}

func (x RiskLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RiskLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_satellite_proto_enumTypes[1].Descriptor()
}

func (RiskLevel) Type() protoreflect.EnumType {
	return &file_satellite_proto_enumTypes[1]
}

func (x RiskLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RiskLevel.Descriptor instead.
func (RiskLevel) EnumDescriptor() ([]byte, []int) {
	return file_satellite_proto_rawDescGZIP(), []int{1}
}

// SatelliteMessage is sent from Satellite to Nexus
type SatelliteMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*SatelliteMessage_RegisterRequest
	//	*SatelliteMessage_TerminalData
	//	*SatelliteMessage_SessionStateUpdate
	//	*SatelliteMessage_IpcEvent
	//	*SatelliteMessage_HeartbeatPing
	//	*SatelliteMessage_TelemetryReport
	//	*SatelliteMessage_BufferReplay
	//	*SatelliteMessage_ProposalRequest
	//	*SatelliteMessage_AgentEvent
	//	*SatelliteMessage_ContextFileUpdate
	//	*SatelliteMessage_ProvisionProgress
	Payload       isSatelliteMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SatelliteMessage) Reset() {
	*x = SatelliteMessage{}
	mi := &file_satellite_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SatelliteMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SatelliteMessage) ProtoMessage() {}

func (x *SatelliteMessage) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SatelliteMessage.ProtoReflect.Descriptor instead.
func (*SatelliteMessage) Descriptor() ([]byte, []int) {
	return file_satellite_proto_rawDescGZIP(), []int{0}
}

func (x *SatelliteMessage) GetPayload() isSatelliteMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SatelliteMessage) GetRegisterRequest() *RegisterRequest {
	if x != nil {
		if x, ok := x.Payload.(*SatelliteMessage_RegisterRequest); ok {
			return x.RegisterRequest
		}
	}
	return nil
}

func (x *SatelliteMessage) GetTerminalData() *TerminalData {
	if x != nil {
		if x, ok := x.Payload.(*SatelliteMessage_TerminalData); ok {
			return x.TerminalData
		}
	}
	return nil
}

func (x *SatelliteMessage) GetSessionStateUpdate() *SessionStateUpdate {
	if x != nil {
		if x, ok := x.Payload.(*SatelliteMessage_SessionStateUpdate); ok {
			return x.SessionStateUpdate
		}
	}
	return nil
}

func (x *SatelliteMessage) GetIpcEvent() *IpcEvent {
	if x != nil {
		if x, ok := x.Payload.(*SatelliteMessage_IpcEvent); ok {
			return x.IpcEvent
		}
	}
	return nil
}

func (x *SatelliteMessage) GetHeartbeatPing() *HeartbeatPing {
	if x != nil {
		if x, ok := x.Payload.(*SatelliteMessage_HeartbeatPing); ok {
			return x.HeartbeatPing
		}
	}
	return nil
}

func (x *SatelliteMessage) GetTelemetryReport() *TelemetryReport {
	if x != nil {
		if x, ok := x.Payload.(*SatelliteMessage_TelemetryReport); ok {
			return x.TelemetryReport
		}
	}
	return nil
}

func (x *SatelliteMessage) GetBufferReplay() *BufferReplay {
	if x != nil {
		if x, ok := x.Payload.(*SatelliteMessage_BufferReplay); ok {
			return x.BufferReplay
		}
	}
	return nil
}

func (x *SatelliteMessage) GetProposalRequest() *ProposalRequest {
	if x != nil {
		if x, ok := x.Payload.(*SatelliteMessage_ProposalRequest); ok {
			return x.ProposalRequest
		}
	}
	return nil
}

func (x *SatelliteMessage) GetAgentEvent() *AgentEvent {
	if x != nil {
		if x, ok := x.Payload.(*SatelliteMessage_AgentEvent); ok {
			return x.AgentEvent
		}
	}
	return nil
}

func (x *SatelliteMessage) GetContextFileUpdate() *ContextFileUpdate {
	if x != nil {
		if x, ok := x.Payload.(*SatelliteMessage_ContextFileUpdate); ok {
			return x.ContextFileUpdate
		}
	}
	return nil
}

func (x *SatelliteMessage) GetProvisionProgress() *ProvisionProgress {
	if x != nil {
		if x, ok := x.Payload.(*SatelliteMessage_ProvisionProgress); ok {
			return x.ProvisionProgress
		}
	}
	return nil
}

type isSatelliteMessage_Payload interface {
	isSatelliteMessage_Payload()
}

type SatelliteMessage_RegisterRequest struct {
	RegisterRequest *RegisterRequest `protobuf:"bytes,1,opt,name=register_request,json=registerRequest,proto3,oneof"`
}

type SatelliteMessage_TerminalData struct {
	TerminalData *TerminalData `protobuf:"bytes,2,opt,name=terminal_data,json=terminalData,proto3,oneof"`
}

type SatelliteMessage_SessionStateUpdate struct {
	SessionStateUpdate *SessionStateUpdate `protobuf:"bytes,3,opt,name=session_state_update,json=sessionStateUpdate,proto3,oneof"`
}

type SatelliteMessage_IpcEvent struct {
	IpcEvent *IpcEvent `protobuf:"bytes,4,opt,name=ipc_event,json=ipcEvent,proto3,oneof"`
}

type SatelliteMessage_HeartbeatPing struct {
	HeartbeatPing *HeartbeatPing `protobuf:"bytes,5,opt,name=heartbeat_ping,json=heartbeatPing,proto3,oneof"`
}

type SatelliteMessage_TelemetryReport struct {
	TelemetryReport *TelemetryReport `protobuf:"bytes,6,opt,name=telemetry_report,json=telemetryReport,proto3,oneof"`
}

type SatelliteMessage_BufferReplay struct {
	BufferReplay *BufferReplay `protobuf:"bytes,7,opt,name=buffer_replay,json=bufferReplay,proto3,oneof"`
}

type SatelliteMessage_ProposalRequest struct {
	ProposalRequest *ProposalRequest `protobuf:"bytes,8,opt,name=proposal_request,json=proposalRequest,proto3,oneof"`
}

type SatelliteMessage_AgentEvent struct {
	AgentEvent *AgentEvent `protobuf:"bytes,9,opt,name=agent_event,json=agentEvent,proto3,oneof"`
}

type SatelliteMessage_ContextFileUpdate struct {
	ContextFileUpdate *ContextFileUpdate `protobuf:"bytes,10,opt,name=context_file_update,json=contextFileUpdate,proto3,oneof"`
}

type SatelliteMessage_ProvisionProgress struct {
	ProvisionProgress *ProvisionProgress `protobuf:"bytes,11,opt,name=provision_progress,json=provisionProgress,proto3,oneof"`
}

func (*SatelliteMessage_RegisterRequest) isSatelliteMessage_Payload() {}

func (*SatelliteMessage_TerminalData) isSatelliteMessage_Payload() {}

func (*SatelliteMessage_SessionStateUpdate) isSatelliteMessage_Payload() {}

func (*SatelliteMessage_IpcEvent) isSatelliteMessage_Payload() {}

func (*SatelliteMessage_HeartbeatPing) isSatelliteMessage_Payload() {}

func (*SatelliteMessage_TelemetryReport) isSatelliteMessage_Payload() {}

func (*SatelliteMessage_BufferReplay) isSatelliteMessage_Payload() {}

func (*SatelliteMessage_ProposalRequest) isSatelliteMessage_Payload() {}

func (*SatelliteMessage_AgentEvent) isSatelliteMessage_Payload() {}

func (*SatelliteMessage_ContextFileUpdate) isSatelliteMessage_Payload() {}

func (*SatelliteMessage_ProvisionProgress) isSatelliteMessage_Payload() {}

// BufferReplay carries a full ring buffer snapshot from a satellite
// session, sent on reconnect so Nexus can rehydrate its in-memory pool.
type BufferReplay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"` // Raw terminal output (Snapshot bytes)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BufferReplay) Reset() {
	*x = BufferReplay{}
	mi := &file_satellite_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BufferReplay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BufferReplay) ProtoMessage() {}

func (x *BufferReplay) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BufferReplay.ProtoReflect.Descriptor instead.
func (*BufferReplay) Descriptor() ([]byte, []int) {
	return file_satellite_proto_rawDescGZIP(), []int{1}
}

func (x *BufferReplay) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *BufferReplay) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// NexusMessage is sent from Nexus to Satellite
type NexusMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*NexusMessage_TerminalInput
	//	*NexusMessage_ResizeCommand
	//	*NexusMessage_SuspendCommand
	//	*NexusMessage_ResumeCommand
	//	*NexusMessage_KillCommand
	//	*NexusMessage_StartSessionCommand
	//	*NexusMessage_UpdateAvailable
	//	*NexusMessage_ProposalDecision
	//	*NexusMessage_DeployAgentCommand
	//	*NexusMessage_ContextFilePush
	//	*NexusMessage_SessionReconciliation
	//	*NexusMessage_ProvisionRuntimeCommand
	Payload       isNexusMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NexusMessage) Reset() {
	*x = NexusMessage{}
	mi := &file_satellite_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NexusMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NexusMessage) ProtoMessage() {}

func (x *NexusMessage) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NexusMessage.ProtoReflect.Descriptor instead.
func (*NexusMessage) Descriptor() ([]byte, []int) {
	return file_satellite_proto_rawDescGZIP(), []int{2}
}

func (x *NexusMessage) GetPayload() isNexusMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *NexusMessage) GetTerminalInput() *TerminalInput {
	if x != nil {
		if x, ok := x.Payload.(*NexusMessage_TerminalInput); ok {
			return x.TerminalInput
		}
	}
	return nil
}

func (x *NexusMessage) GetResizeCommand() *ResizeCommand {
	if x != nil {
		if x, ok := x.Payload.(*NexusMessage_ResizeCommand); ok {
			return x.ResizeCommand
		}
	}
	return nil
}

func (x *NexusMessage) GetSuspendCommand() *SuspendCommand {
	if x != nil {
		if x, ok := x.Payload.(*NexusMessage_SuspendCommand); ok {
			return x.SuspendCommand
		}
	}
	return nil
}

func (x *NexusMessage) GetResumeCommand() *ResumeCommand {
	if x != nil {
		if x, ok := x.Payload.(*NexusMessage_ResumeCommand); ok {
			return x.ResumeCommand
		}
	}
	return nil
}

func (x *NexusMessage) GetKillCommand() *KillCommand {
	if x != nil {
		if x, ok := x.Payload.(*NexusMessage_KillCommand); ok {
			return x.KillCommand
		}
	}
	return nil
}

func (x *NexusMessage) GetStartSessionCommand() *StartSessionCommand {
	if x != nil {
		if x, ok := x.Payload.(*NexusMessage_StartSessionCommand); ok {
			return x.StartSessionCommand
		}
	}
	return nil
}

func (x *NexusMessage) GetUpdateAvailable() *UpdateAvailable {
	if x != nil {
		if x, ok := x.Payload.(*NexusMessage_UpdateAvailable); ok {
			return x.UpdateAvailable
		}
	}
	return nil
}

func (x *NexusMessage) GetProposalDecision() *ProposalDecision {
	if x != nil {
		if x, ok := x.Payload.(*NexusMessage_ProposalDecision); ok {
			return x.ProposalDecision
		}
	}
	return nil
}

func (x *NexusMessage) GetDeployAgentCommand() *DeployAgentCommand {
	if x != nil {
		if x, ok := x.Payload.(*NexusMessage_DeployAgentCommand); ok {
			return x.DeployAgentCommand
		}
	}
	return nil
}

func (x *NexusMessage) GetContextFilePush() *ContextFilePush {
	if x != nil {
		if x, ok := x.Payload.(*NexusMessage_ContextFilePush); ok {
			return x.ContextFilePush
		}
	}
	return nil
}

func (x *NexusMessage) GetSessionReconciliation() *SessionReconciliation {
	if x != nil {
		if x, ok := x.Payload.(*NexusMessage_SessionReconciliation); ok {
			return x.SessionReconciliation
		}
	}
	return nil
}

func (x *NexusMessage) GetProvisionRuntimeCommand() *ProvisionRuntimeCommand {
	if x != nil {
		if x, ok := x.Payload.(*NexusMessage_ProvisionRuntimeCommand); ok {
			return x.ProvisionRuntimeCommand
		}
	}
	return nil
}

type isNexusMessage_Payload interface {
	isNexusMessage_Payload()
}

type NexusMessage_TerminalInput struct {
	TerminalInput *TerminalInput `protobuf:"bytes,1,opt,name=terminal_input,json=terminalInput,proto3,oneof"`
}

type NexusMessage_ResizeCommand struct {
	ResizeCommand *ResizeCommand `protobuf:"bytes,2,opt,name=resize_command,json=resizeCommand,proto3,oneof"`
}

type NexusMessage_SuspendCommand struct {
	SuspendCommand *SuspendCommand `protobuf:"bytes,3,opt,name=suspend_command,json=suspendCommand,proto3,oneof"`
}

type NexusMessage_ResumeCommand struct {
	ResumeCommand *ResumeCommand `protobuf:"bytes,4,opt,name=resume_command,json=resumeCommand,proto3,oneof"`
}

type NexusMessage_KillCommand struct {
	KillCommand *KillCommand `protobuf:"bytes,5,opt,name=kill_command,json=killCommand,proto3,oneof"`
}

type NexusMessage_StartSessionCommand struct {
	StartSessionCommand *StartSessionCommand `protobuf:"bytes,6,opt,name=start_session_command,json=startSessionCommand,proto3,oneof"`
}

type NexusMessage_UpdateAvailable struct {
	UpdateAvailable *UpdateAvailable `protobuf:"bytes,7,opt,name=update_available,json=updateAvailable,proto3,oneof"`
}

type NexusMessage_ProposalDecision struct {
	ProposalDecision *ProposalDecision `protobuf:"bytes,8,opt,name=proposal_decision,json=proposalDecision,proto3,oneof"`
}

type NexusMessage_DeployAgentCommand struct {
	DeployAgentCommand *DeployAgentCommand `protobuf:"bytes,9,opt,name=deploy_agent_command,json=deployAgentCommand,proto3,oneof"`
}

type NexusMessage_ContextFilePush struct {
	ContextFilePush *ContextFilePush `protobuf:"bytes,10,opt,name=context_file_push,json=contextFilePush,proto3,oneof"`
}

type NexusMessage_SessionReconciliation struct {
	SessionReconciliation *SessionReconciliation `protobuf:"bytes,11,opt,name=session_reconciliation,json=sessionReconciliation,proto3,oneof"`
}

type NexusMessage_ProvisionRuntimeCommand struct {
	ProvisionRuntimeCommand *ProvisionRuntimeCommand `protobuf:"bytes,12,opt,name=provision_runtime_command,json=provisionRuntimeCommand,proto3,oneof"`
}

func (*NexusMessage_TerminalInput) isNexusMessage_Payload() {}

func (*NexusMessage_ResizeCommand) isNexusMessage_Payload() {}

func (*NexusMessage_SuspendCommand) isNexusMessage_Payload() {}

func (*NexusMessage_ResumeCommand) isNexusMessage_Payload() {}

func (*NexusMessage_KillCommand) isNexusMessage_Payload() {}

func (*NexusMessage_StartSessionCommand) isNexusMessage_Payload() {}

func (*NexusMessage_UpdateAvailable) isNexusMessage_Payload() {}

func (*NexusMessage_ProposalDecision) isNexusMessage_Payload() {}

func (*NexusMessage_DeployAgentCommand) isNexusMessage_Payload() {}

func (*NexusMessage_ContextFilePush) isNexusMessage_Payload() {}

func (*NexusMessage_SessionReconciliation) isNexusMessage_Payload() {}

func (*NexusMessage_ProvisionRuntimeCommand) isNexusMessage_Payload() {}

// SessionReconciliation is sent from Nexus to Satellite after registration.
// Contains the authoritative list of active sessions for this satellite so
// the satellite can prune any orphan sessions that Nexus no longer knows about.
type SessionReconciliation struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ActiveSessionIds []string               `protobuf:"bytes,1,rep,name=active_session_ids,json=activeSessionIds,proto3" json:"active_session_ids,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SessionReconciliation) Reset() {
	*x = SessionReconciliation{}
	mi := &file_satellite_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionReconciliation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionReconciliation) ProtoMessage() {}

func (x *SessionReconciliation) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionReconciliation.ProtoReflect.Descriptor instead.
func (*SessionReconciliation) Descriptor() ([]byte, []int) {
	return file_satellite_proto_rawDescGZIP(), []int{3}
}

func (x *SessionReconciliation) GetActiveSessionIds() []string {
	if x != nil {
		return x.ActiveSessionIds
	}
	return nil
}

// StartSessionCommand creates and starts a new session process on the satellite
type StartSessionCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AgentBinary   string                 `protobuf:"bytes,2,opt,name=agent_binary,json=agentBinary,proto3" json:"agent_binary,omitempty"`
	AgentArgs     []string               `protobuf:"bytes,3,rep,name=agent_args,json=agentArgs,proto3" json:"agent_args,omitempty"`
	Cols          int32                  `protobuf:"varint,4,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          int32                  `protobuf:"varint,5,opt,name=rows,proto3" json:"rows,omitempty"`
	WorkingDir    string                 `protobuf:"bytes,6,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSessionCommand) Reset() {
	*x = StartSessionCommand{}
	mi := &file_satellite_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionCommand) ProtoMessage() {}

func (x *StartSessionCommand) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionCommand.ProtoReflect.Descriptor instead.
func (*StartSessionCommand) Descriptor() ([]byte, []int) {
	return file_satellite_proto_rawDescGZIP(), []int{4}
}

func (x *StartSessionCommand) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StartSessionCommand) GetAgentBinary() string {
	if x != nil {
		return x.AgentBinary
	}
	return ""
}

func (x *StartSessionCommand) GetAgentArgs() []string {
	if x != nil {
		return x.AgentArgs
	}
	return nil
}

func (x *StartSessionCommand) GetCols() int32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *StartSessionCommand) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *StartSessionCommand) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

// RegisterRequest is sent when a satellite connects
type RegisterRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SatelliteId     string                 `protobuf:"bytes,1,opt,name=satellite_id,json=satelliteId,proto3" json:"satellite_id,omitempty"`
	Fingerprint     string                 `protobuf:"bytes,2,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	PublicKey       string                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Timestamp       int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Version         string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`                                        // Satellite binary version (e.g. "v1.2.3")
	Os              string                 `protobuf:"bytes,6,opt,name=os,proto3" json:"os,omitempty"`                                                  // runtime.GOOS (e.g. "windows", "linux", "darwin")
	Arch            string                 `protobuf:"bytes,7,opt,name=arch,proto3" json:"arch,omitempty"`                                              // runtime.GOARCH (e.g. "amd64", "arm64")
	AvailableAgents []string               `protobuf:"bytes,8,rep,name=available_agents,json=availableAgents,proto3" json:"available_agents,omitempty"` // Agent binaries found on this satellite
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_satellite_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_satellite_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterRequest) GetSatelliteId() string {
	if x != nil {
		return x.SatelliteId
	}
	return ""
}

func (x *RegisterRequest) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *RegisterRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *RegisterRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *RegisterRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *RegisterRequest) GetAvailableAgents() []string {
	if x != nil {
		return x.AvailableAgents
	}
	return nil
}

// TerminalData carries terminal output from a session
type TerminalData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Data           []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	SequenceNumber int64                  `protobuf:"varint,3,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Timestamp      int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	IsStdout       bool                   `protobuf:"varint,5,opt,name=is_stdout,json=isStdout,proto3" json:"is_stdout,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TerminalData) Reset() {
	*x = TerminalData{}
	mi := &file_satellite_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalData) ProtoMessage() {}

func (x *TerminalData) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalData.ProtoReflect.Descriptor instead.
func (*TerminalData) Descriptor() ([]byte, []int) {
	return file_satellite_proto_rawDescGZIP(), []int{6}
}

func (x *TerminalData) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TerminalData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TerminalData) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *TerminalData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TerminalData) GetIsStdout() bool {
	if x != nil {
		return x.IsStdout
	}
	return false
}

// SessionStateUpdate carries session state changes
type SessionStateUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	State         SessionState           `protobuf:"varint,2,opt,name=state,proto3,enum=nexus.SessionState" json:"state,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionStateUpdate) Reset() {
	*x = SessionStateUpdate{}
	mi := &file_satellite_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStateUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStateUpdate) ProtoMessage() {}

func (x *SessionStateUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStateUpdate.ProtoReflect.Descriptor instead.
func (*SessionStateUpdate) Descriptor() ([]byte, []int) {
	return file_satellite_proto_rawDescGZIP(), []int{7}
}

func (x *SessionStateUpdate) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionStateUpdate) GetState() SessionState {
	if x != nil {
		return x.State
	}
	return SessionState_SESSION_STATE_UNSPECIFIED
}

func (x *SessionStateUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SessionStateUpdate) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// IpcEvent carries IPC events between processes
type IpcEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IpcEvent) Reset() {
	*x = IpcEvent{}
	mi := &file_satellite_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IpcEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpcEvent) ProtoMessage() {}

func (x *IpcEvent) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpcEvent.ProtoReflect.Descriptor instead.
func (*IpcEvent) Descriptor() ([]byte, []int) {
	return file_satellite_proto_rawDescGZIP(), []int{8}
}

func (x *IpcEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *IpcEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *IpcEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *IpcEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// HeartbeatPing keeps the stream alive and detects connectivity
type HeartbeatPing struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Timestamp      int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SequenceNumber int64                  `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatPing) Reset() {
	*x = HeartbeatPing{}
	mi := &file_satellite_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatPing) ProtoMessage() {}

func (x *HeartbeatPing) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatPing.ProtoReflect.Descriptor instead.
func (*HeartbeatPing) Descriptor() ([]byte, []int) {
	return file_satellite_proto_rawDescGZIP(), []int{9}
}

func (x *HeartbeatPing) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatPing) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

// TerminalInput sends terminal input to a session
type TerminalInput struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Data           []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	SequenceNumber int64                  `protobuf:"varint,3,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TerminalInput) Reset() {
	*x = TerminalInput{}
	mi := &file_satellite_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalInput) ProtoMessage() {}

func (x *TerminalInput) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalInput.ProtoReflect.Descriptor instead.
func (*TerminalInput) Descriptor() ([]byte, []int) {
	return file_satellite_proto_rawDescGZIP(), []int{10}
}

func (x *TerminalInput) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TerminalInput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TerminalInput) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

// ResizeCommand resizes a terminal session
type ResizeCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	PixelWidth    int32                  `protobuf:"varint,4,opt,name=pixel_width,json=pixelWidth,proto3" json:"pixel_width,omitempty"`
	PixelHeight   int32                  `protobuf:"varint,5,opt,name=pixel_height,json=pixelHeight,proto3" json:"pixel_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResizeCommand) Reset() {
	*x = ResizeCommand{}
	mi := &file_satellite_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizeCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeCommand) ProtoMessage() {}

func (x *ResizeCommand) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeCommand.ProtoReflect.Descriptor instead.
func (*ResizeCommand) Descriptor() ([]byte, []int) {
	return file_satellite_proto_rawDescGZIP(), []int{11}
}

func (x *ResizeCommand) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ResizeCommand) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ResizeCommand) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ResizeCommand) GetPixelWidth() int32 {
	if x != nil {
		return x.PixelWidth
	}
	return 0
}

func (x *ResizeCommand) GetPixelHeight() int32 {
	if x != nil {
		return x.PixelHeight
	}
	return 0
}

// SuspendCommand suspends a running session
type SuspendCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuspendCommand) Reset() {
	*x = SuspendCommand{}
	mi := &file_satellite_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspendCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspendCommand) ProtoMessage() {}

func (x *SuspendCommand) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspendCommand.ProtoReflect.Descriptor instead.
func (*SuspendCommand) Descriptor() ([]byte, []int) {
	return file_satellite_proto_rawDescGZIP(), []int{12}
}

func (x *SuspendCommand) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// ResumeCommand resumes a suspended session
type ResumeCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeCommand) Reset() {
	*x = ResumeCommand{}
	mi := &file_satellite_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeCommand) ProtoMessage() {}

func (x *ResumeCommand) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeCommand.ProtoReflect.Descriptor instead.
func (*ResumeCommand) Descriptor() ([]byte, []int) {
	return file_satellite_proto_rawDescGZIP(), []int{13}
}

func (x *ResumeCommand) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// KillCommand terminates a session
type KillCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillCommand) Reset() {
	*x = KillCommand{}
	mi := &file_satellite_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillCommand) ProtoMessage() {}

func (x *KillCommand) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillCommand.ProtoReflect.Descriptor instead.
func (*KillCommand) Descriptor() ([]byte, []int) {
	return file_satellite_proto_rawDescGZIP(), []int{14}
}

func (x *KillCommand) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *KillCommand) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

// UpdateAvailable is sent from Nexus to a satellite when a newer version exists
type UpdateAvailable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LatestVersion string                 `protobuf:"bytes,1,opt,name=latest_version,json=latestVersion,proto3" json:"latest_version,omitempty"` // The newest version available on the server
	DownloadUrl   string                 `protobuf:"bytes,2,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`       // Full URL to download the binary
	Force         bool                   `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`                                     // If true, satellite should auto-update immediately
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAvailable) Reset() {
	*x = UpdateAvailable{}
	mi := &file_satellite_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAvailable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAvailable) ProtoMessage() {}

func (x *UpdateAvailable) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAvailable.ProtoReflect.Descriptor instead.
func (*UpdateAvailable) Descriptor() ([]byte, []int) {
	return file_satellite_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateAvailable) GetLatestVersion() string {
	if x != nil {
		return x.LatestVersion
	}
	return ""
}

func (x *UpdateAvailable) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *UpdateAvailable) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// ProposalRequest is sent from Satellite to Nexus when an AI agent
// calls daao.proposeAction to request human approval for a command.
type ProposalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`                       // Session the AI agent is running in
	ProposalId    string                 `protobuf:"bytes,2,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`                    // Unique proposal ID (generated by satellite)
	Command       string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`                                            // The command the AI wants to execute
	Justification string                 `protobuf:"bytes,4,opt,name=justification,proto3" json:"justification,omitempty"`                                // AI's explanation of why this command is needed
	RiskLevel     RiskLevel              `protobuf:"varint,5,opt,name=risk_level,json=riskLevel,proto3,enum=nexus.RiskLevel" json:"risk_level,omitempty"` // Severity assessment
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SatelliteId   string                 `protobuf:"bytes,7,opt,name=satellite_id,json=satelliteId,proto3" json:"satellite_id,omitempty"` // Satellite where the command would execute
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposalRequest) Reset() {
	*x = ProposalRequest{}
	mi := &file_satellite_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposalRequest) ProtoMessage() {}

func (x *ProposalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposalRequest.ProtoReflect.Descriptor instead.
func (*ProposalRequest) Descriptor() ([]byte, []int) {
	return file_satellite_proto_rawDescGZIP(), []int{16}
}

func (x *ProposalRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ProposalRequest) GetProposalId() string {
	if x != nil {
		return x.ProposalId
	}
	return ""
}

func (x *ProposalRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ProposalRequest) GetJustification() string {
	if x != nil {
		return x.Justification
	}
	return ""
}

func (x *ProposalRequest) GetRiskLevel() RiskLevel {
	if x != nil {
		return x.RiskLevel
	}
	return RiskLevel_RISK_LEVEL_UNSPECIFIED
}

func (x *ProposalRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ProposalRequest) GetSatelliteId() string {
	if x != nil {
		return x.SatelliteId
	}
	return ""
}

// ProposalDecision is sent from Nexus to Satellite after a human
// approves or denies a proposal in the Cockpit.
type ProposalDecision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ProposalId    string                 `protobuf:"bytes,2,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	Approved      bool                   `protobuf:"varint,3,opt,name=approved,proto3" json:"approved,omitempty"`                      // true = approved, false = denied
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`                           // Optional reason from the human reviewer
	ApproverId    string                 `protobuf:"bytes,5,opt,name=approver_id,json=approverId,proto3" json:"approver_id,omitempty"` // UUID of the user who made the decision
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposalDecision) Reset() {
	*x = ProposalDecision{}
	mi := &file_satellite_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposalDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposalDecision) ProtoMessage() {}

func (x *ProposalDecision) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposalDecision.ProtoReflect.Descriptor instead.
func (*ProposalDecision) Descriptor() ([]byte, []int) {
	return file_satellite_proto_rawDescGZIP(), []int{17}
}

func (x *ProposalDecision) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ProposalDecision) GetProposalId() string {
	if x != nil {
		return x.ProposalId
	}
	return ""
}

func (x *ProposalDecision) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *ProposalDecision) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ProposalDecision) GetApproverId() string {
	if x != nil {
		return x.ApproverId
	}
	return ""
}

func (x *ProposalDecision) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// TelemetryReport carries system metrics from a satellite
type TelemetryReport struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SatelliteId      string                 `protobuf:"bytes,1,opt,name=satellite_id,json=satelliteId,proto3" json:"satellite_id,omitempty"`
	CpuPercent       float64                `protobuf:"fixed64,2,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`          // 0-100 overall CPU utilisation
	MemoryPercent    float64                `protobuf:"fixed64,3,opt,name=memory_percent,json=memoryPercent,proto3" json:"memory_percent,omitempty"` // 0-100 memory utilisation
	MemoryUsedBytes  int64                  `protobuf:"varint,4,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	MemoryTotalBytes int64                  `protobuf:"varint,5,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3" json:"memory_total_bytes,omitempty"`
	DiskPercent      float64                `protobuf:"fixed64,6,opt,name=disk_percent,json=diskPercent,proto3" json:"disk_percent,omitempty"` // 0-100 root/primary disk utilisation
	DiskUsedBytes    int64                  `protobuf:"varint,7,opt,name=disk_used_bytes,json=diskUsedBytes,proto3" json:"disk_used_bytes,omitempty"`
	DiskTotalBytes   int64                  `protobuf:"varint,8,opt,name=disk_total_bytes,json=diskTotalBytes,proto3" json:"disk_total_bytes,omitempty"`
	Gpus             []*GpuMetrics          `protobuf:"bytes,9,rep,name=gpus,proto3" json:"gpus,omitempty"`
	Timestamp        int64                  `protobuf:"varint,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ActiveSessions   int32                  `protobuf:"varint,11,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	AvailableAgents  []string               `protobuf:"bytes,12,rep,name=available_agents,json=availableAgents,proto3" json:"available_agents,omitempty"` // Agent binaries currently available
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TelemetryReport) Reset() {
	*x = TelemetryReport{}
	mi := &file_satellite_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryReport) ProtoMessage() {}

func (x *TelemetryReport) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryReport.ProtoReflect.Descriptor instead.
func (*TelemetryReport) Descriptor() ([]byte, []int) {
	return file_satellite_proto_rawDescGZIP(), []int{18}
}

func (x *TelemetryReport) GetSatelliteId() string {
	if x != nil {
		return x.SatelliteId
	}
	return ""
}

func (x *TelemetryReport) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *TelemetryReport) GetMemoryPercent() float64 {
	if x != nil {
		return x.MemoryPercent
	}
	return 0
}

func (x *TelemetryReport) GetMemoryUsedBytes() int64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *TelemetryReport) GetMemoryTotalBytes() int64 {
	if x != nil {
		return x.MemoryTotalBytes
	}
	return 0
}

func (x *TelemetryReport) GetDiskPercent() float64 {
	if x != nil {
		return x.DiskPercent
	}
	return 0
}

func (x *TelemetryReport) GetDiskUsedBytes() int64 {
	if x != nil {
		return x.DiskUsedBytes
	}
	return 0
}

func (x *TelemetryReport) GetDiskTotalBytes() int64 {
	if x != nil {
		return x.DiskTotalBytes
	}
	return 0
}

func (x *TelemetryReport) GetGpus() []*GpuMetrics {
	if x != nil {
		return x.Gpus
	}
	return nil
}

func (x *TelemetryReport) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TelemetryReport) GetActiveSessions() int32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

func (x *TelemetryReport) GetAvailableAgents() []string {
	if x != nil {
		return x.AvailableAgents
	}
	return nil
}

// GpuMetrics carries per-GPU metrics
type GpuMetrics struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Index              int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UtilizationPercent float64                `protobuf:"fixed64,3,opt,name=utilization_percent,json=utilizationPercent,proto3" json:"utilization_percent,omitempty"` // 0-100 GPU core utilisation
	MemoryUsedBytes    int64                  `protobuf:"varint,4,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	MemoryTotalBytes   int64                  `protobuf:"varint,5,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3" json:"memory_total_bytes,omitempty"`
	TemperatureCelsius float64                `protobuf:"fixed64,6,opt,name=temperature_celsius,json=temperatureCelsius,proto3" json:"temperature_celsius,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GpuMetrics) Reset() {
	*x = GpuMetrics{}
	mi := &file_satellite_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GpuMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GpuMetrics) ProtoMessage() {}

func (x *GpuMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GpuMetrics.ProtoReflect.Descriptor instead.
func (*GpuMetrics) Descriptor() ([]byte, []int) {
	return file_satellite_proto_rawDescGZIP(), []int{19}
}

func (x *GpuMetrics) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *GpuMetrics) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GpuMetrics) GetUtilizationPercent() float64 {
	if x != nil {
		return x.UtilizationPercent
	}
	return 0
}

func (x *GpuMetrics) GetMemoryUsedBytes() int64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *GpuMetrics) GetMemoryTotalBytes() int64 {
	if x != nil {
		return x.MemoryTotalBytes
	}
	return 0
}

func (x *GpuMetrics) GetTemperatureCelsius() float64 {
	if x != nil {
		return x.TemperatureCelsius
	}
	return 0
}

// AgentDefinitionProto defines an agent that can be deployed to a satellite
type AgentDefinitionProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                                                               // Agent name (e.g., "code-agent", "task-executor")
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`                                                                         // Agent version (e.g., "v1.0.0")
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`                                                                             // Container image or binary path
	Config        map[string]string      `protobuf:"bytes,4,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Agent configuration key-value pairs
	Capabilities  []string               `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"`                                                               // Agent capabilities
	Entrypoint    string                 `protobuf:"bytes,6,opt,name=entrypoint,proto3" json:"entrypoint,omitempty"`                                                                   // Entry point command or script
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentDefinitionProto) Reset() {
	*x = AgentDefinitionProto{}
	mi := &file_satellite_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentDefinitionProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentDefinitionProto) ProtoMessage() {}

func (x *AgentDefinitionProto) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentDefinitionProto.ProtoReflect.Descriptor instead.
func (*AgentDefinitionProto) Descriptor() ([]byte, []int) {
	return file_satellite_proto_rawDescGZIP(), []int{20}
}

func (x *AgentDefinitionProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentDefinitionProto) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentDefinitionProto) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *AgentDefinitionProto) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *AgentDefinitionProto) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *AgentDefinitionProto) GetEntrypoint() string {
	if x != nil {
		return x.Entrypoint
	}
	return ""
}

// DeployAgentCommand is sent from Nexus to Satellite to deploy an agent
type DeployAgentCommand struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`                                                      // Session to deploy the agent into
	AgentDefinition *AgentDefinitionProto  `protobuf:"bytes,2,opt,name=agent_definition,json=agentDefinition,proto3" json:"agent_definition,omitempty"`                                    // The agent to deploy
	Secrets         map[string]string      `protobuf:"bytes,3,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Secrets for the agent (API keys, tokens, etc.)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeployAgentCommand) Reset() {
	*x = DeployAgentCommand{}
	mi := &file_satellite_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployAgentCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployAgentCommand) ProtoMessage() {}

func (x *DeployAgentCommand) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployAgentCommand.ProtoReflect.Descriptor instead.
func (*DeployAgentCommand) Descriptor() ([]byte, []int) {
	return file_satellite_proto_rawDescGZIP(), []int{21}
}

func (x *DeployAgentCommand) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DeployAgentCommand) GetAgentDefinition() *AgentDefinitionProto {
	if x != nil {
		return x.AgentDefinition
	}
	return nil
}

func (x *DeployAgentCommand) GetSecrets() map[string]string {
	if x != nil {
		return x.Secrets
	}
	return nil
}

// AgentEvent is sent from Satellite to Nexus to report agent events
type AgentEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // Session where the event occurred
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // Event type (e.g., "started", "stopped", "error", "output")
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`                      // Event-specific data
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                 // Unix timestamp in milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentEvent) Reset() {
	*x = AgentEvent{}
	mi := &file_satellite_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEvent) ProtoMessage() {}

func (x *AgentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEvent.ProtoReflect.Descriptor instead.
func (*AgentEvent) Descriptor() ([]byte, []int) {
	return file_satellite_proto_rawDescGZIP(), []int{22}
}

func (x *AgentEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AgentEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *AgentEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// ContextFileSync carries file synchronization data for agent context
type ContextFileSync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SatelliteId   string                 `protobuf:"bytes,1,opt,name=satellite_id,json=satelliteId,proto3" json:"satellite_id,omitempty"` // Source satellite ID
	FilePath      string                 `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`          // Path to the file
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                            // File content
	Version       int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`                           // File version number
	ModifiedBy    string                 `protobuf:"bytes,5,opt,name=modified_by,json=modifiedBy,proto3" json:"modified_by,omitempty"`    // Who modified the file (agent name, user, etc.)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextFileSync) Reset() {
	*x = ContextFileSync{}
	mi := &file_satellite_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextFileSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextFileSync) ProtoMessage() {}

func (x *ContextFileSync) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextFileSync.ProtoReflect.Descriptor instead.
func (*ContextFileSync) Descriptor() ([]byte, []int) {
	return file_satellite_proto_rawDescGZIP(), []int{23}
}

func (x *ContextFileSync) GetSatelliteId() string {
	if x != nil {
		return x.SatelliteId
	}
	return ""
}

func (x *ContextFileSync) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *ContextFileSync) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ContextFileSync) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ContextFileSync) GetModifiedBy() string {
	if x != nil {
		return x.ModifiedBy
	}
	return ""
}

// ContextFilePush is sent from Nexus to Satellite to push file updates
type ContextFilePush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *ContextFileSync       `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"` // The file to sync
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextFilePush) Reset() {
	*x = ContextFilePush{}
	mi := &file_satellite_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextFilePush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextFilePush) ProtoMessage() {}

func (x *ContextFilePush) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextFilePush.ProtoReflect.Descriptor instead.
func (*ContextFilePush) Descriptor() ([]byte, []int) {
	return file_satellite_proto_rawDescGZIP(), []int{24}
}

func (x *ContextFilePush) GetFile() *ContextFileSync {
	if x != nil {
		return x.File
	}
	return nil
}

// ContextFileUpdate is sent from Satellite to Nexus to report file changes
type ContextFileUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *ContextFileSync       `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"` // The updated file
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextFileUpdate) Reset() {
	*x = ContextFileUpdate{}
	mi := &file_satellite_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextFileUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextFileUpdate) ProtoMessage() {}

func (x *ContextFileUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextFileUpdate.ProtoReflect.Descriptor instead.
func (*ContextFileUpdate) Descriptor() ([]byte, []int) {
	return file_satellite_proto_rawDescGZIP(), []int{25}
}

func (x *ContextFileUpdate) GetFile() *ContextFileSync {
	if x != nil {
		return x.File
	}
	return nil
}

// ProvisionRuntimeCommand triggers runtime bootstrap on a satellite.
// Sent from Nexus to Satellite (e.g., when admin clicks "Provision" in Cockpit).
type ProvisionRuntimeCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Force         bool                   `protobuf:"varint,1,opt,name=force,proto3" json:"force,omitempty"` // If true, re-install even if runtime already exists
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionRuntimeCommand) Reset() {
	*x = ProvisionRuntimeCommand{}
	mi := &file_satellite_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionRuntimeCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionRuntimeCommand) ProtoMessage() {}

func (x *ProvisionRuntimeCommand) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionRuntimeCommand.ProtoReflect.Descriptor instead.
func (*ProvisionRuntimeCommand) Descriptor() ([]byte, []int) {
	return file_satellite_proto_rawDescGZIP(), []int{26}
}

func (x *ProvisionRuntimeCommand) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// ProvisionProgress reports bootstrap progress from Satellite to Nexus.
// Streamed during bootstrap so Cockpit can show real-time provisioning status.
type ProvisionProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Step          string                 `protobuf:"bytes,1,opt,name=step,proto3" json:"step,omitempty"`          // Step identifier: "download_node", "install_pi", "complete", "error"
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`    // Human-readable status message
	Complete      bool                   `protobuf:"varint,3,opt,name=complete,proto3" json:"complete,omitempty"` // True when provisioning is finished (success or failure)
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`        // Non-empty when the step failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionProgress) Reset() {
	*x = ProvisionProgress{}
	mi := &file_satellite_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionProgress) ProtoMessage() {}

func (x *ProvisionProgress) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionProgress.ProtoReflect.Descriptor instead.
func (*ProvisionProgress) Descriptor() ([]byte, []int) {
	return file_satellite_proto_rawDescGZIP(), []int{27}
}

func (x *ProvisionProgress) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *ProvisionProgress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProvisionProgress) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

func (x *ProvisionProgress) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_satellite_proto protoreflect.FileDescriptor

const file_satellite_proto_rawDesc = "" +
	"\n" +
	"\x0fsatellite.proto\x12\x05nexus\"\xef\x05\n" +
	"\x10SatelliteMessage\x12C\n" +
	"\x10register_request\x18\x01 \x01(\v2\x16.nexus.RegisterRequestH\x00R\x0fregisterRequest\x12:\n" +
	"\rterminal_data\x18\x02 \x01(\v2\x13.nexus.TerminalDataH\x00R\fterminalData\x12M\n" +
	"\x14session_state_update\x18\x03 \x01(\v2\x19.nexus.SessionStateUpdateH\x00R\x12sessionStateUpdate\x12.\n" +
	"\tipc_event\x18\x04 \x01(\v2\x0f.nexus.IpcEventH\x00R\bipcEvent\x12=\n" +
	"\x0eheartbeat_ping\x18\x05 \x01(\v2\x14.nexus.HeartbeatPingH\x00R\rheartbeatPing\x12C\n" +
	"\x10telemetry_report\x18\x06 \x01(\v2\x16.nexus.TelemetryReportH\x00R\x0ftelemetryReport\x12:\n" +
	"\rbuffer_replay\x18\a \x01(\v2\x13.nexus.BufferReplayH\x00R\fbufferReplay\x12C\n" +
	"\x10proposal_request\x18\b \x01(\v2\x16.nexus.ProposalRequestH\x00R\x0fproposalRequest\x124\n" +
	"\vagent_event\x18\t \x01(\v2\x11.nexus.AgentEventH\x00R\n" +
	"agentEvent\x12J\n" +
	"\x13context_file_update\x18\n" +
	" \x01(\v2\x18.nexus.ContextFileUpdateH\x00R\x11contextFileUpdate\x12I\n" +
	"\x12provision_progress\x18\v \x01(\v2\x18.nexus.ProvisionProgressH\x00R\x11provisionProgressB\t\n" +
	"\apayload\"A\n" +
	"\fBufferReplay\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\xfa\x06\n" +
	"\fNexusMessage\x12=\n" +
	"\x0eterminal_input\x18\x01 \x01(\v2\x14.nexus.TerminalInputH\x00R\rterminalInput\x12=\n" +
	"\x0eresize_command\x18\x02 \x01(\v2\x14.nexus.ResizeCommandH\x00R\rresizeCommand\x12@\n" +
	"\x0fsuspend_command\x18\x03 \x01(\v2\x15.nexus.SuspendCommandH\x00R\x0esuspendCommand\x12=\n" +
	"\x0eresume_command\x18\x04 \x01(\v2\x14.nexus.ResumeCommandH\x00R\rresumeCommand\x127\n" +
	"\fkill_command\x18\x05 \x01(\v2\x12.nexus.KillCommandH\x00R\vkillCommand\x12P\n" +
	"\x15start_session_command\x18\x06 \x01(\v2\x1a.nexus.StartSessionCommandH\x00R\x13startSessionCommand\x12C\n" +
	"\x10update_available\x18\a \x01(\v2\x16.nexus.UpdateAvailableH\x00R\x0fupdateAvailable\x12F\n" +
	"\x11proposal_decision\x18\b \x01(\v2\x17.nexus.ProposalDecisionH\x00R\x10proposalDecision\x12M\n" +
	"\x14deploy_agent_command\x18\t \x01(\v2\x19.nexus.DeployAgentCommandH\x00R\x12deployAgentCommand\x12D\n" +
	"\x11context_file_push\x18\n" +
	" \x01(\v2\x16.nexus.ContextFilePushH\x00R\x0fcontextFilePush\x12U\n" +
	"\x16session_reconciliation\x18\v \x01(\v2\x1c.nexus.SessionReconciliationH\x00R\x15sessionReconciliation\x12\\\n" +
	"\x19provision_runtime_command\x18\f \x01(\v2\x1e.nexus.ProvisionRuntimeCommandH\x00R\x17provisionRuntimeCommandB\t\n" +
	"\apayload\"E\n" +
	"\x15SessionReconciliation\x12,\n" +
	"\x12active_session_ids\x18\x01 \x03(\tR\x10activeSessionIds\"\xbf\x01\n" +
	"\x13StartSessionCommand\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12!\n" +
	"\fagent_binary\x18\x02 \x01(\tR\vagentBinary\x12\x1d\n" +
	"\n" +
	"agent_args\x18\x03 \x03(\tR\tagentArgs\x12\x12\n" +
	"\x04cols\x18\x04 \x01(\x05R\x04cols\x12\x12\n" +
	"\x04rows\x18\x05 \x01(\x05R\x04rows\x12\x1f\n" +
	"\vworking_dir\x18\x06 \x01(\tR\n" +
	"workingDir\"\xfc\x01\n" +
	"\x0fRegisterRequest\x12!\n" +
	"\fsatellite_id\x18\x01 \x01(\tR\vsatelliteId\x12 \n" +
	"\vfingerprint\x18\x02 \x01(\tR\vfingerprint\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKey\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12\x0e\n" +
	"\x02os\x18\x06 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\a \x01(\tR\x04arch\x12)\n" +
	"\x10available_agents\x18\b \x03(\tR\x0favailableAgents\"\xa5\x01\n" +
	"\fTerminalData\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12'\n" +
	"\x0fsequence_number\x18\x03 \x01(\x03R\x0esequenceNumber\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\tis_stdout\x18\x05 \x01(\bR\bisStdout\"\xa1\x01\n" +
	"\x12SessionStateUpdate\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12)\n" +
	"\x05state\x18\x02 \x01(\x0e2\x13.nexus.SessionStateR\x05state\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"\x80\x01\n" +
	"\bIpcEvent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"V\n" +
	"\rHeartbeatPing\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12'\n" +
	"\x0fsequence_number\x18\x02 \x01(\x03R\x0esequenceNumber\"k\n" +
	"\rTerminalInput\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12'\n" +
	"\x0fsequence_number\x18\x03 \x01(\x03R\x0esequenceNumber\"\xa0\x01\n" +
	"\rResizeCommand\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12\x1f\n" +
	"\vpixel_width\x18\x04 \x01(\x05R\n" +
	"pixelWidth\x12!\n" +
	"\fpixel_height\x18\x05 \x01(\x05R\vpixelHeight\"/\n" +
	"\x0eSuspendCommand\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\".\n" +
	"\rResumeCommand\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"I\n" +
	"\vKillCommand\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\"q\n" +
	"\x0fUpdateAvailable\x12%\n" +
	"\x0elatest_version\x18\x01 \x01(\tR\rlatestVersion\x12!\n" +
	"\fdownload_url\x18\x02 \x01(\tR\vdownloadUrl\x12\x14\n" +
	"\x05force\x18\x03 \x01(\bR\x05force\"\x83\x02\n" +
	"\x0fProposalRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vproposal_id\x18\x02 \x01(\tR\n" +
	"proposalId\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12$\n" +
	"\rjustification\x18\x04 \x01(\tR\rjustification\x12/\n" +
	"\n" +
	"risk_level\x18\x05 \x01(\x0e2\x10.nexus.RiskLevelR\triskLevel\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12!\n" +
	"\fsatellite_id\x18\a \x01(\tR\vsatelliteId\"\xc5\x01\n" +
	"\x10ProposalDecision\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vproposal_id\x18\x02 \x01(\tR\n" +
	"proposalId\x12\x1a\n" +
	"\bapproved\x18\x03 \x01(\bR\bapproved\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x1f\n" +
	"\vapprover_id\x18\x05 \x01(\tR\n" +
	"approverId\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"\xe4\x03\n" +
	"\x0fTelemetryReport\x12!\n" +
	"\fsatellite_id\x18\x01 \x01(\tR\vsatelliteId\x12\x1f\n" +
	"\vcpu_percent\x18\x02 \x01(\x01R\n" +
	"cpuPercent\x12%\n" +
	"\x0ememory_percent\x18\x03 \x01(\x01R\rmemoryPercent\x12*\n" +
	"\x11memory_used_bytes\x18\x04 \x01(\x03R\x0fmemoryUsedBytes\x12,\n" +
	"\x12memory_total_bytes\x18\x05 \x01(\x03R\x10memoryTotalBytes\x12!\n" +
	"\fdisk_percent\x18\x06 \x01(\x01R\vdiskPercent\x12&\n" +
	"\x0fdisk_used_bytes\x18\a \x01(\x03R\rdiskUsedBytes\x12(\n" +
	"\x10disk_total_bytes\x18\b \x01(\x03R\x0ediskTotalBytes\x12%\n" +
	"\x04gpus\x18\t \x03(\v2\x11.nexus.GpuMetricsR\x04gpus\x12\x1c\n" +
	"\ttimestamp\x18\n" +
	" \x01(\x03R\ttimestamp\x12'\n" +
	"\x0factive_sessions\x18\v \x01(\x05R\x0eactiveSessions\x12)\n" +
	"\x10available_agents\x18\f \x03(\tR\x0favailableAgents\"\xf2\x01\n" +
	"\n" +
	"GpuMetrics\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12/\n" +
	"\x13utilization_percent\x18\x03 \x01(\x01R\x12utilizationPercent\x12*\n" +
	"\x11memory_used_bytes\x18\x04 \x01(\x03R\x0fmemoryUsedBytes\x12,\n" +
	"\x12memory_total_bytes\x18\x05 \x01(\x03R\x10memoryTotalBytes\x12/\n" +
	"\x13temperature_celsius\x18\x06 \x01(\x01R\x12temperatureCelsius\"\x9a\x02\n" +
	"\x14AgentDefinitionProto\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12?\n" +
	"\x06config\x18\x04 \x03(\v2'.nexus.AgentDefinitionProto.ConfigEntryR\x06config\x12\"\n" +
	"\fcapabilities\x18\x05 \x03(\tR\fcapabilities\x12\x1e\n" +
	"\n" +
	"entrypoint\x18\x06 \x01(\tR\n" +
	"entrypoint\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf9\x01\n" +
	"\x12DeployAgentCommand\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12F\n" +
	"\x10agent_definition\x18\x02 \x01(\v2\x1b.nexus.AgentDefinitionProtoR\x0fagentDefinition\x12@\n" +
	"\asecrets\x18\x03 \x03(\v2&.nexus.DeployAgentCommand.SecretsEntryR\asecrets\x1a:\n" +
	"\fSecretsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x82\x01\n" +
	"\n" +
	"AgentEvent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\xa6\x01\n" +
	"\x0fContextFileSync\x12!\n" +
	"\fsatellite_id\x18\x01 \x01(\tR\vsatelliteId\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\x12\x1f\n" +
	"\vmodified_by\x18\x05 \x01(\tR\n" +
	"modifiedBy\"=\n" +
	"\x0fContextFilePush\x12*\n" +
	"\x04file\x18\x01 \x01(\v2\x16.nexus.ContextFileSyncR\x04file\"?\n" +
	"\x11ContextFileUpdate\x12*\n" +
	"\x04file\x18\x01 \x01(\v2\x16.nexus.ContextFileSyncR\x04file\"/\n" +
	"\x17ProvisionRuntimeCommand\x12\x14\n" +
	"\x05force\x18\x01 \x01(\bR\x05force\"s\n" +
	"\x11ProvisionProgress\x12\x12\n" +
	"\x04step\x18\x01 \x01(\tR\x04step\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1a\n" +
	"\bcomplete\x18\x03 \x01(\bR\bcomplete\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error*\xf4\x01\n" +
	"\fSessionState\x12\x1d\n" +
	"\x19SESSION_STATE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16SESSION_STATE_STARTING\x10\x01\x12\x19\n" +
	"\x15SESSION_STATE_RUNNING\x10\x02\x12\x1b\n" +
	"\x17SESSION_STATE_SUSPENDED\x10\x03\x12\x1c\n" +
	"\x18SESSION_STATE_TERMINATED\x10\x04\x12\x17\n" +
	"\x13SESSION_STATE_ERROR\x10\x05\x12\x1a\n" +
	"\x16SESSION_STATE_DETACHED\x10\x06\x12\x1e\n" +
	"\x1aSESSION_STATE_RE_ATTACHING\x10\a*\x80\x01\n" +
	"\tRiskLevel\x12\x1a\n" +
	"\x16RISK_LEVEL_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eRISK_LEVEL_LOW\x10\x01\x12\x15\n" +
	"\x11RISK_LEVEL_MEDIUM\x10\x02\x12\x13\n" +
	"\x0fRISK_LEVEL_HIGH\x10\x03\x12\x17\n" +
	"\x13RISK_LEVEL_CRITICAL\x10\x042O\n" +
	"\x10SatelliteGateway\x12;\n" +
	"\aConnect\x12\x17.nexus.SatelliteMessage\x1a\x13.nexus.NexusMessage(\x010\x01B\x1dZ\x1bgithub.com/daao/nexus/protob\x06proto3"

var (
	file_satellite_proto_rawDescOnce sync.Once
	file_satellite_proto_rawDescData []byte
)

func file_satellite_proto_rawDescGZIP() []byte {
	file_satellite_proto_rawDescOnce.Do(func() {
		file_satellite_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_satellite_proto_rawDesc), len(file_satellite_proto_rawDesc)))
	})
	return file_satellite_proto_rawDescData
}

var file_satellite_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_satellite_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_satellite_proto_goTypes = []any{
	(SessionState)(0),               // 0: nexus.SessionState
	(RiskLevel)(0),                  // 1: nexus.RiskLevel
	(*SatelliteMessage)(nil),        // 2: nexus.SatelliteMessage
	(*BufferReplay)(nil),            // 3: nexus.BufferReplay
	(*NexusMessage)(nil),            // 4: nexus.NexusMessage
	(*SessionReconciliation)(nil),   // 5: nexus.SessionReconciliation
	(*StartSessionCommand)(nil),     // 6: nexus.StartSessionCommand
	(*RegisterRequest)(nil),         // 7: nexus.RegisterRequest
	(*TerminalData)(nil),            // 8: nexus.TerminalData
	(*SessionStateUpdate)(nil),      // 9: nexus.SessionStateUpdate
	(*IpcEvent)(nil),                // 10: nexus.IpcEvent
	(*HeartbeatPing)(nil),           // 11: nexus.HeartbeatPing
	(*TerminalInput)(nil),           // 12: nexus.TerminalInput
	(*ResizeCommand)(nil),           // 13: nexus.ResizeCommand
	(*SuspendCommand)(nil),          // 14: nexus.SuspendCommand
	(*ResumeCommand)(nil),           // 15: nexus.ResumeCommand
	(*KillCommand)(nil),             // 16: nexus.KillCommand
	(*UpdateAvailable)(nil),         // 17: nexus.UpdateAvailable
	(*ProposalRequest)(nil),         // 18: nexus.ProposalRequest
	(*ProposalDecision)(nil),        // 19: nexus.ProposalDecision
	(*TelemetryReport)(nil),         // 20: nexus.TelemetryReport
	(*GpuMetrics)(nil),              // 21: nexus.GpuMetrics
	(*AgentDefinitionProto)(nil),    // 22: nexus.AgentDefinitionProto
	(*DeployAgentCommand)(nil),      // 23: nexus.DeployAgentCommand
	(*AgentEvent)(nil),              // 24: nexus.AgentEvent
	(*ContextFileSync)(nil),         // 25: nexus.ContextFileSync
	(*ContextFilePush)(nil),         // 26: nexus.ContextFilePush
	(*ContextFileUpdate)(nil),       // 27: nexus.ContextFileUpdate
	(*ProvisionRuntimeCommand)(nil), // 28: nexus.ProvisionRuntimeCommand
	(*ProvisionProgress)(nil),       // 29: nexus.ProvisionProgress
	nil,                             // 30: nexus.AgentDefinitionProto.ConfigEntry
	nil,                             // 31: nexus.DeployAgentCommand.SecretsEntry
}
var file_satellite_proto_depIdxs = []int32{
	7,  // 0: nexus.SatelliteMessage.register_request:type_name -> nexus.RegisterRequest
	8,  // 1: nexus.SatelliteMessage.terminal_data:type_name -> nexus.TerminalData
	9,  // 2: nexus.SatelliteMessage.session_state_update:type_name -> nexus.SessionStateUpdate
	10, // 3: nexus.SatelliteMessage.ipc_event:type_name -> nexus.IpcEvent
	11, // 4: nexus.SatelliteMessage.heartbeat_ping:type_name -> nexus.HeartbeatPing
	20, // 5: nexus.SatelliteMessage.telemetry_report:type_name -> nexus.TelemetryReport
	3,  // 6: nexus.SatelliteMessage.buffer_replay:type_name -> nexus.BufferReplay
	18, // 7: nexus.SatelliteMessage.proposal_request:type_name -> nexus.ProposalRequest
	24, // 8: nexus.SatelliteMessage.agent_event:type_name -> nexus.AgentEvent
	27, // 9: nexus.SatelliteMessage.context_file_update:type_name -> nexus.ContextFileUpdate
	29, // 10: nexus.SatelliteMessage.provision_progress:type_name -> nexus.ProvisionProgress
	12, // 11: nexus.NexusMessage.terminal_input:type_name -> nexus.TerminalInput
	13, // 12: nexus.NexusMessage.resize_command:type_name -> nexus.ResizeCommand
	14, // 13: nexus.NexusMessage.suspend_command:type_name -> nexus.SuspendCommand
	15, // 14: nexus.NexusMessage.resume_command:type_name -> nexus.ResumeCommand
	16, // 15: nexus.NexusMessage.kill_command:type_name -> nexus.KillCommand
	6,  // 16: nexus.NexusMessage.start_session_command:type_name -> nexus.StartSessionCommand
	17, // 17: nexus.NexusMessage.update_available:type_name -> nexus.UpdateAvailable
	19, // 18: nexus.NexusMessage.proposal_decision:type_name -> nexus.ProposalDecision
	23, // 19: nexus.NexusMessage.deploy_agent_command:type_name -> nexus.DeployAgentCommand
	26, // 20: nexus.NexusMessage.context_file_push:type_name -> nexus.ContextFilePush
	5,  // 21: nexus.NexusMessage.session_reconciliation:type_name -> nexus.SessionReconciliation
	28, // 22: nexus.NexusMessage.provision_runtime_command:type_name -> nexus.ProvisionRuntimeCommand
	0,  // 23: nexus.SessionStateUpdate.state:type_name -> nexus.SessionState
	1,  // 24: nexus.ProposalRequest.risk_level:type_name -> nexus.RiskLevel
	21, // 25: nexus.TelemetryReport.gpus:type_name -> nexus.GpuMetrics
	30, // 26: nexus.AgentDefinitionProto.config:type_name -> nexus.AgentDefinitionProto.ConfigEntry
	22, // 27: nexus.DeployAgentCommand.agent_definition:type_name -> nexus.AgentDefinitionProto
	31, // 28: nexus.DeployAgentCommand.secrets:type_name -> nexus.DeployAgentCommand.SecretsEntry
	25, // 29: nexus.ContextFilePush.file:type_name -> nexus.ContextFileSync
	25, // 30: nexus.ContextFileUpdate.file:type_name -> nexus.ContextFileSync
	2,  // 31: nexus.SatelliteGateway.Connect:input_type -> nexus.SatelliteMessage
	4,  // 32: nexus.SatelliteGateway.Connect:output_type -> nexus.NexusMessage
	32, // [32:33] is the sub-list for method output_type
	31, // [31:32] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_satellite_proto_init() }
func file_satellite_proto_init() {
	if File_satellite_proto != nil {
		return
	}
	file_satellite_proto_msgTypes[0].OneofWrappers = []any{
		(*SatelliteMessage_RegisterRequest)(nil),
		(*SatelliteMessage_TerminalData)(nil),
		(*SatelliteMessage_SessionStateUpdate)(nil),
		(*SatelliteMessage_IpcEvent)(nil),
		(*SatelliteMessage_HeartbeatPing)(nil),
		(*SatelliteMessage_TelemetryReport)(nil),
		(*SatelliteMessage_BufferReplay)(nil),
		(*SatelliteMessage_ProposalRequest)(nil),
		(*SatelliteMessage_AgentEvent)(nil),
		(*SatelliteMessage_ContextFileUpdate)(nil),
		(*SatelliteMessage_ProvisionProgress)(nil),
	}
	file_satellite_proto_msgTypes[2].OneofWrappers = []any{
		(*NexusMessage_TerminalInput)(nil),
		(*NexusMessage_ResizeCommand)(nil),
		(*NexusMessage_SuspendCommand)(nil),
		(*NexusMessage_ResumeCommand)(nil),
		(*NexusMessage_KillCommand)(nil),
		(*NexusMessage_StartSessionCommand)(nil),
		(*NexusMessage_UpdateAvailable)(nil),
		(*NexusMessage_ProposalDecision)(nil),
		(*NexusMessage_DeployAgentCommand)(nil),
		(*NexusMessage_ContextFilePush)(nil),
		(*NexusMessage_SessionReconciliation)(nil),
		(*NexusMessage_ProvisionRuntimeCommand)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_satellite_proto_rawDesc), len(file_satellite_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_satellite_proto_goTypes,
		DependencyIndexes: file_satellite_proto_depIdxs,
		EnumInfos:         file_satellite_proto_enumTypes,
		MessageInfos:      file_satellite_proto_msgTypes,
	}.Build()
	File_satellite_proto = out.File
	file_satellite_proto_goTypes = nil
	file_satellite_proto_depIdxs = nil
}
