// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.1
// source: satellite.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SatelliteGateway_Connect_FullMethodName = "/nexus.SatelliteGateway/Connect"
)

// SatelliteGatewayClient is the client API for SatelliteGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SatelliteGateway service for bidirectional streaming between Satellite and Nexus
type SatelliteGatewayClient interface {
	// Connect establishes a bidirectional stream for session communication
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SatelliteMessage, NexusMessage], error)
}

type satelliteGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewSatelliteGatewayClient(cc grpc.ClientConnInterface) SatelliteGatewayClient {
	return &satelliteGatewayClient{cc}
}

func (c *satelliteGatewayClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SatelliteMessage, NexusMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SatelliteGateway_ServiceDesc.Streams[0], SatelliteGateway_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SatelliteMessage, NexusMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SatelliteGateway_ConnectClient = grpc.BidiStreamingClient[SatelliteMessage, NexusMessage]

// SatelliteGatewayServer is the server API for SatelliteGateway service.
// All implementations must embed UnimplementedSatelliteGatewayServer
// for forward compatibility.
//
// SatelliteGateway service for bidirectional streaming between Satellite and Nexus
type SatelliteGatewayServer interface {
	// Connect establishes a bidirectional stream for session communication
	Connect(grpc.BidiStreamingServer[SatelliteMessage, NexusMessage]) error
	mustEmbedUnimplementedSatelliteGatewayServer()
}

// UnimplementedSatelliteGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSatelliteGatewayServer struct{}

func (UnimplementedSatelliteGatewayServer) Connect(grpc.BidiStreamingServer[SatelliteMessage, NexusMessage]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedSatelliteGatewayServer) mustEmbedUnimplementedSatelliteGatewayServer() {}
func (UnimplementedSatelliteGatewayServer) testEmbeddedByValue()                          {}

// UnsafeSatelliteGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SatelliteGatewayServer will
// result in compilation errors.
type UnsafeSatelliteGatewayServer interface {
	mustEmbedUnimplementedSatelliteGatewayServer()
}

func RegisterSatelliteGatewayServer(s grpc.ServiceRegistrar, srv SatelliteGatewayServer) {
	// If the following call panics, it indicates UnimplementedSatelliteGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SatelliteGateway_ServiceDesc, srv)
}

func _SatelliteGateway_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SatelliteGatewayServer).Connect(&grpc.GenericServerStream[SatelliteMessage, NexusMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SatelliteGateway_ConnectServer = grpc.BidiStreamingServer[SatelliteMessage, NexusMessage]

// SatelliteGateway_ServiceDesc is the grpc.ServiceDesc for SatelliteGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SatelliteGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nexus.SatelliteGateway",
	HandlerType: (*SatelliteGatewayServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _SatelliteGateway_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "satellite.proto",
}
